git:
  quiet: true

language: minimal

addons:
  apt:
    packages:
      - neovim
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - shellcheck
      - vim-nox
    sources:
      - sourceline: ppa:neovim-ppa/unstable
  homebrew:
    update: true
    packages:
      - neovim
      - python@3
      - shellcheck

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=1

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
    - os: osx
      osx_image: xcode11
      rvm: system
    - os: osx
      osx_image: xcode9.4
      rvm: system
    - os: osx
      osx_image: xcode9.2
      rvm: system

install: ./.ci/install.sh
script: ./.ci/script.sh

deploy:
  on:
    tags: true
  provider: releases
  api_key: 'GITHUB_OAUTH_TOKEN'
  skip_cleanup: true
  draft: true
  prerelease: true

notifications:
  email: false
