git:
  quiet: true

language: minimal

addons:
  apt: &apt
    packages: &apt-packages
      - neovim
      - shellcheck
      - vim-nox
    sources:
      - sourceline: ppa:neovim-ppa/unstable
  homebrew:
    update: true
    packages:
      - neovim
      - python@3

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=1

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      addons: &addons-bionic
        apt:
          <<: *apt
          packages:
            - *apt-packages
            - python3-pip
            - python3-setuptools
            - python3-wheel
    - os: linux
      dist: xenial
      addons:
        <<: *addons-bionic
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode11.2
      rvm: system
    - os: osx
      osx_image: xcode10.3
      rvm: system
    - os: osx
      osx_image: xcode10.1
      rvm: system

install: ./.ci/install.sh
script: ./.ci/script.sh

deploy:
  on:
    tags: true
  provider: releases
  api_key: 'GITHUB_OAUTH_TOKEN'
  skip_cleanup: true
  draft: true
  prerelease: true

notifications:
  email: false
