language: minimal

addons:
  apt:
    packages:
      - neovim
      - shellcheck
      - vim-nox
    sources:
      - sourceline: ppa:neovim-ppa/unstable
  homebrew:
    packages:
      - neovim
      - shellcheck

matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: osx
    - os: windows

install: ./.ci/install.sh
script: ./.ci/script.sh

notifications:
  email: false
