language: go
go:
  - 1.8

addons:
  apt:
    packages:
      - vim-nox
      - neovim
    sources:
      - sourceline: ppa:neovim-ppa/unstable
  homebrew:
    packages:
      - neovim

matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: osx
    - os: windows

install: ./.ci/install.sh
script: ./.ci/script.sh

notifications:
  email: false
