sudo: false
dist: trusty

language: go
go:
  - 1.8

env:
  global:
    # Do not include subtrees   ex. vim-plug
    - VIM_FILES="vimrc gvimrc $(git ls-files '*.vim' | grep -v 'plug.vim' | tr \\n ' ')"

before_install:
  - echo $VIM_FILES

install:
  - go get github.com/haya14busa/go-vimlparser/cmd/vimlparser

script:
  - vimlparser $VIM_FILES > /dev/null

notifications:
  email: false
