name: CI
on:
  push:
    branches: '**'

jobs:
  unix:
    name: ${{ matrix.os }} - ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            runner: ubuntu-22.04
          - os: linux
            runner: ubuntu-24.04
          - os: linux
            runner: ubuntu-latest
          - os: osx
            runner: macos-15
          - os: osx
            runner: macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - if: matrix.os == 'linux'
        run: |
          sudo apt-get -q update
          sudo apt-get install -q -y --no-install-recommends neovim
          command -v nvim
          nvim --version
      - if: matrix.os == 'osx'
        run: |
          brew update >/dev/null
          brew install neovim
          command -v nvim
          nvim --version
      - run: sh .ci/script.sh
  windows:
    name: ${{ matrix.os }} - ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            runner: windows-2025
          - os: windows
            runner: windows-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          $env:SCOOP = "$PWD/.scoop"
          iwr -useb get.scoop.sh | iex
          scoop install neovim
          where.exe nvim
          nvim --version
          sh .ci/script.sh
