name: CI
on:
  push:
    branches: '**'

jobs:
  test:
    name: ${{ matrix.os }} - ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            runner: ubuntu-16.04
          - os: linux
            runner: ubuntu-18.04
          - os: linux
            runner: ubuntu-20.04
          - os: osx
            runner: macos-10.15
          - os: osx
            runner: macos-11.0
          - os: windows
            runner: windows-2016
          - os: windows
            runner: windows-2019
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache vim-plug bundles
        uses: actions/cache@v2
        with:
          path: bundle
          key: vim-plug
      - run: sh .ci/script.sh
